config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('crm/', include('crm.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.urls import path

from . import views
from .views import clients_delete

urlpatterns = [
    path('login/', views.login_user, name="login_user"),
    path('home/', views.index, name="home"),
    path('clients/', views.clients, name="clients"),
    path('clients_delete/<str:pk>', clients_delete, name='clients_delete'),
    path('offic/', views.offic, name="offic"),
    # path('edit_offic/<int:pk>', views.edit_offic, name="edit_offic_pk"),
    path('department_<pk>/', views.department, name="department"),
    path('service', views.service, name="service"),
    path('settings', views.settings, name="settings"),
    path('archive/', views.archive, name="archive"),
    path('order_archived/<int:pk>', views.oreders_archived, name="order_archived"),
    path('log_out', views.sign_out, name="sign_out"),
    path('edit_percent_<pk>/', views.edit_percent, name='edit_percent')
]

crm/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

# Create your models here.
from crm.querysets.project_service import ProjectServiceQuerySet

ROLE = {
    ('Manager', 'Manager'),
}


class User(AbstractUser):
    name = models.CharField(max_length=120)
    password = models.CharField(max_length=120)
    role = models.CharField(max_length=120, choices=ROLE)
    objects = UserManager()

    def __str__(self):
        return self.username + ' ' + self.role


FROM = {
    ('Instagram', 'Instagram'),
    ('Facebook', 'Facebook'),
}


class ClientsStatus(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Clients(models.Model):
    creat_date = models.DateTimeField(auto_now_add=True)
    birthday = models.DateField(null=True, blank=True)
    full_name = models.CharField(max_length=120)
    phone = models.IntegerField(null=True)
    address = models.CharField(max_length=120, null=True)
    manager = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.ForeignKey(ClientsStatus, null=True, blank=True, on_delete=models.CASCADE)
    form = models.CharField(max_length=120, choices=FROM, null=True)

    def __str__(self):
        return self.full_name


STATUS_PAY = {
    ('Оплачено', 'Оплачено'),
    ('Аванс', 'Аванс'),
    ('Ожидание', 'Ожидание'),
}


class Orders(models.Model):
    order_number = models.IntegerField(null=True)
    title = models.CharField(max_length=120)
    service = models.ManyToManyField('Service', through="ProjectService")
    client = models.ForeignKey(Clients, on_delete=models.CASCADE)
    status = models.CharField(max_length=120, choices=STATUS_PAY, default="Ожидание")
    is_archive = models.BooleanField(default=False, null=True, blank=True)
    numbers = models.PositiveIntegerField(null=True, blank=True)
    user = models.ManyToManyField('User')

    def __str__(self):
        return f"Clientni ismi: {self.client}, Buyurtma: {self.title}"


class Department(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=120)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey('Service', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ProjectService(models.Model):
    order = models.ForeignKey(Orders, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ManyToManyField('User', null=True, blank=True, )
    parcent = models.FloatField(default=0, null=True, blank=True)
    max_parcent = models.IntegerField(default=0, null=True, blank=True)

    objects = ProjectServiceQuerySet.as_manager()

    def total_prince(self):
        return int(self.order.numbers * (self.parcent / 100))


class OrderField(models.Model):
    title = models.CharField(max_length=255)
    field = models.FileField(upload_to='uploads/', blank=False)
    order_filed = models.ForeignKey(Orders, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

crm/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Clients, Orders, Service, User, OrderField, ProjectService


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-[#EF4D23] transition duration-150 ease-in-out sm:text-sm sm:leading-5"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-[#EF4D23] transition duration-150 ease-in-out sm:text-sm sm:leading-5"
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class ClientForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'tel', 'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    manager = forms.SelectMultiple()
    status = forms.SelectMultiple()
    form = forms.SelectMultiple()
    birthday = forms.DateField(widget=forms.DateInput(format='d.m.y', attrs={
        'type': 'date', 'placeholder': 'Select Date'
    }))

    class Meta:
        model = Clients
        fields = ('full_name', 'phone', 'address', 'status', 'manager', 'form', 'birthday')


class OrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].queryset = Service.objects.filter(parent=None)

    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    order_number = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    numbers = forms.CharField(widget=forms.NumberInput(attrs={
        'type': 'number', 'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    client = forms.SelectMultiple()
    status = forms.SelectMultiple()
    user = forms.ModelMultipleChoiceField(queryset=User.objects.all(), widget=forms.CheckboxSelectMultiple)
    service = forms.ModelMultipleChoiceField(queryset=Service.objects.filter(parent=None),
                                             widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Orders
        fields = ('title', 'order_number', 'client', 'status', 'service', 'numbers', 'user')


class ServiceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].queryset = Service.objects.filter(parent=None)

    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))

    class Meta:
        model = Service
        fields = ('name', 'department', 'parent')


class EditOrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = ('title', 'order_number', 'client', 'status', 'numbers', 'user')


class OrderFieldForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    field = forms.FileField()

    class Meta:
        model = OrderField
        fields = ('title', 'field')


class ProjectServiceForm(forms.ModelForm):
    parcent = forms.CharField(widget=forms.NumberInput(attrs={
        'class': 'border px-[5px] group-hover:bg-gray-100 transition-colors'
    }))
    max_parcent = forms.IntegerField()

    user = forms.ModelMultipleChoiceField(queryset=User.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = ProjectService
        fields = ('parcent', 'max_parcent', 'user')

crm/views.py
from django.contrib.auth import login, logout
from django.dispatch import receiver
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
from .forms import *
from .models import Clients, Orders, Service, Department, ProjectService, OrderField, ClientsStatus, FROM, User, \
    STATUS_PAY


def login_user(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            print(user)
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('home')
    return render(request, 'sign_in.html', {'form': form})


@login_required(login_url='/login_user')
def index(request):
    return render(request, 'index.html')


@login_required(login_url='/login_user')
def clients(request):
    clients = Clients.objects.all()
    statuses = ClientsStatus.objects.all()
    form = ClientForm(request.POST)
    users = User.objects.all()
    print(request.POST)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('clients')
    if request.POST.get("id", None):
        client = clients.filter(id=request.POST.get('id'))
        client.update(
            full_name=request.POST.get('full_name'),
            phone=request.POST.get('phone'),
            address=request.POST.get('address'),
            form=request.POST.get('form'),
            birthday=request.POST.get('birthday'),
            status=request.POST.get('status'),
        )
        # return redirect('clients')

    return render(request, 'clients.html',
                  {'clients': clients,
                   'statuses': statuses,
                   "form": form,
                   'klients_count': Clients.objects.count(),
                   'users': users,
                   })


def clients_delete(request, pk):
    clients_delete = Clients.objects.get(pk=pk)
    clients_delete.delete()
    return redirect('clients')


def offic(request):
    services = Service.objects.filter(Q(parent__isnull=False))
    orders = Orders.objects.filter(user=request.user)
    departments = Department.objects.all()
    form = OrderForm(request.POST)

    if form.is_valid() and request.method == 'POST':
        instance = form.save(commit=False)
        instance.save()
        form.save_m2m()

        for i in request.POST.getlist('service'):
            services = Service.objects.filter(parent=i)

            for service in services:
                project_service = ProjectService()
                project_service.service = service
                project_service.parcent = 0
                project_service.max_parcent = 0
                project_service.save()
        return redirect('offic')

    service_edit = Service.objects.filter(Q(parent__isnull=True))
    client_edit = Clients.objects.all()
    user_edit = User.objects.all()
    status_edit = STATUS_PAY
    print(request.POST)
    client, order_id, user, service, numbers, title, order_number = (
        request.POST.get('client'),
        request.POST.get('order_id'),
        request.POST.getlist('username'),
        request.POST.getlist('service'),
        request.POST.get('numbers'),
        request.POST.get('title'),
        request.POST.get('order_number'),
    )
    if client and request.method == 'POST':
        pp = Orders.objects.filter(id=order_id)
        pp.update(
            client=client,
            numbers=numbers,
            title=title,
            order_number=order_number
        )
        pp = pp.first()

        for uu in pp.user.all():
            if str(uu.id) not in user:
                pp.user.remove(str(uu.id))

        for u in user:
            pp.user.add(u)

        for ss in pp.service.all():
            if str(ss.id) not in service:
                pp.service.remove(str(ss.id))

        for i in service:
            services = Service.objects.filter(parent=i)
            for service in services:
                pp.service.add(service.id)

        return redirect('offic')
    return render(request, 'ofis.html',
                  {'orders': orders,
                   'departments': departments,
                   'form': form,
                   'order_count': Orders.objects.filter(is_archive=False).count(),
                   'services': services,
                   'service_edit': service_edit,
                   'client_edit': client_edit,
                   'user_edit': user_edit,
                   'status_edit': status_edit
                   })


def archive(request):
    order_archive = Orders.objects.filter(is_archive=True)
    return render(request, 'archive.html', {
        'orders': order_archive,
        'order_count': Orders.objects.filter(is_archive=True).count(),
    })


def oreders_archived(request, pk):
    order_archived = Orders.objects.filter(pk=pk)
    if order_archived.first().is_archive:
        order_archived.update(is_archive=False)
        return redirect('archive')
    else:
        order_archived.update(is_archive=True)
    return redirect('offic')


# def edit_offic(request, pk):
#     print('***********************')
#     order = Orders.objects.get(id=pk)
#     form = EditOrderForm(request.POST or None, instance=order)
#     if form.is_valid() and request.method == 'POST':
#         form.save()
#         return redirect('offic')
#     return render(request, 'edit_offic.html',
#                   {'order': order,
#                    'formEdit': form})


def service(request):
    services = Service.objects.all()
    form = ServiceForm(request.POST)
    if form.is_valid() and request.method == 'POST':
        instance = form.save(commit=False)
        instance.type = request.POST.get('parent')
        instance.save()
        return redirect('service')
    return render(request, 'spravitcik.html',
                  {'form': form,
                   'services': services})


def settings(request):
    return render(request, 'settings.html')


def department(request, pk):
    orders = Orders.objects.get(pk=pk, user=request.user)
    order_fields = OrderField.objects.filter(order_filed_id=orders)
    form = OrderFieldForm(request.POST or None, request.FILES or None)
    percent, max_percent, user, project_serves_id = (
        request.POST.get('percent'),
        request.POST.get('max_parcent'),
        request.POST.getlist('username'),
        request.POST.get('project_serves_id'),
    )

    if request.method == "POST" and form.is_valid():
        instance = form.save(commit=False)
        instance.order_filed = orders
        instance.save()
        return redirect('department', pk=pk)

    if percent and max_percent and request.method == 'POST':
        pp = ProjectService.objects.filter(id=project_serves_id)
        pp.update(
            parcent=percent,
            max_parcent=max_percent,
        )
        pp = pp.first()

        for uu in pp.user.all():
            if str(uu.id) not in user:
                pp.user.remove(str(uu.id))

        for u in user:
            pp.user.add(u)

        return redirect('department', pk=pk)

    projectservices = ProjectService.objects.filter(order=orders, service__parent__isnull=False)
    result_parcent = 0
    reuslt_sum = 0
    sum_percent = 0
    max_percent_sum = 0
    for item in projectservices:
        result_parcent += item.parcent
        reuslt_sum += item.total_prince()
        max_percent_sum += item.max_parcent
        sum_percent += (item.parcent * item.max_parcent) / 100
    return render(request, 'department.html',
                  {'orders': orders,
                   'projectservices': projectservices,
                   'order_fields': order_fields,
                   'form': form,
                   'result_parcent': result_parcent,
                   'reuslt_sum': reuslt_sum,
                   'sum_percent': sum_percent,
                   'max_percent_sum': 0 if result_parcent == 0 else int((sum_percent / result_parcent) * 100),
                   'result': reuslt_sum * max_percent_sum / 100
                   })


def sign_out(request):
    logout(request)
    return redirect('login_user')


def edit_percent(request, pk):
    project_service = {'id': pk, **request.POST}
    update = ProjectService.objects.edit(project_service)
    return JsonResponse([update.order.pk], safe=False)

crm/templates/clients.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <div class="container mx-auto px-[40px] text-[#051937]">
        <div class="p-[20px] flex items-center justify-between font-bold">
            <div class="flex">
                <h1 class='text-[25px]'>ВСЕ КЛИЕНТЫ</h1>
                <span class='ml-[20px] text-[20px] text-white bg-[#EF4D23] py-[5px] px-[10px] rounded-[10px]'>{{ klients_count }}</span>
            </div>
            <button data-btn="clientCreat"
                    class='btn-open border p-[10px] font-bold text-[#EF4D23] m-[10px] rounded-[15px] hover:border-[#EF4D23] cursor-pointer'>
                + Добавить
            </button>
        </div>

        <div class='flex justify-between'>
            {% for status in statuses %}
                <div class="flex flex-col w-[100%]">
                    <div class="border-b-2 border-[#EF4D23] text-center p-[10px] font-bold">
                        {{ status.name }}
                    </div>
                    {% for client in status.clients_set.all %}
                        <div class=" border m-[10px] p-[10px] rounded-[15px] font-semibold text-[12px] flex flex-col">
                            <div class="flex justify-between items-center gap-[8px]">
                                {{ client.full_name }}
                                <span id="client" data-id="{{ client.id }}" data-btn="clientInfo"
                                      class="text-[20px] hover:text-[#EF4D23] cursor-pointer">:</span>
                            </div>
                            <h1 class="text-[#EF4D23]">{{ client.manager }}</h1>
                            <a href="tel:+{{ client.phone }}" class='hover:text-[#EF4D23]'>+{{ client.phone }}</a>
                        </div>
                        {#                         Model edit star #}
                        <div id="client_edit_modal{{ client.id }}"
                             class='hidden clientModalEdit fixed top-0 left-0 flex justify-center items-center bg-black/[.54] w-[100vw] h-[100vh] z-[99]'>
                            <div class="bg-[#ffff] w-[500px] shadow-2xl rounded-[10px]">
                                <div class="py-[10px] px-[20px] border-b border-[#EF4D23] text-[#EF4D23]">
                                    <h3>Информация:</h3>
                                </div>
                                <div class="py-[20px] px-[20px]">
                                    <form action="" method="post" id="formModalEdit">
                                        {% csrf_token %}
                                        <table class="w-full text-[#051937] ">
                                            <tbody class="w-100%">
                                            <tr class="w-96 hover:bg-gray-100 transition-colors group">
                                                <td class="py-4 px-4 text-start">Ф.И.О:</td>
                                                <td class="py-4 px-4 text-start">
                                                    <input class="hidden" type="text" name="id" value="{{ client.id }}">
                                                    <input class="rounded border px-[5px]" name="full_name" type="text"
                                                           value="{{ client.full_name }}">
                                                </td>
                                            </tr>
                                            <tr class="w-96 hover:bg-gray-100 transition-colors group">
                                                <td class="py-4 px-4 text-start">Номер телефона:</td>
                                                <td class="py-4 px-4 text-start">
                                                    <input class="rounded border px-[5px]" name="phone" type="tel"
                                                           value="{{ client.phone }}">
                                                </td>
                                            </tr>
                                            <tr class="w-96 hover:bg-gray-100 transition-colors group">
                                                <td class="py-4 px-4 text-start">Адрес:</td>
                                                <td class="py-4 px-4 text-start"><input class="rounded border px-[5px]"
                                                                                        name="address" type="text"
                                                                                        value="{{ client.address }}">
                                                </td>
                                            </tr>
                                            <tr class="w-96 hover:bg-gray-100 transition-colors group">
                                                <td class="py-4 px-4 text-start">Менеджер продаж:</td>
                                                <td class="py-4 px-4 text-start">
                                                    <select name="manager">
                                                        <option hidden
                                                                value="{{ client.manager.id }}">{{ client.manager }}</option>
                                                        {% for u in users %}
                                                            <option value="{{ u.id }}">{{ u }}</option>
                                                        {% endfor %}
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr class="w-96 hover:bg-gray-100 transition-colors group">
                                                <td class="py-4 px-4 text-start">Канал продаж:</td>
                                                <td class="py-4 px-4 text-start">
                                                    <input type="text" name="form" value="{{ client.form }}">
                                                    <select>
                                                        <option>{{ from }}</option>
                                                    </select>
                                                </td>

                                            </tr>
                                            <tr class="w-96 hover:bg-gray-100 transition-colors group">
                                                <td class="py-4 px-4 text-start">День рождения:</td>
                                                <td class="py-4 px-4 text-start">
                                                    <input
                                                            class="group-hover:bg-gray-100 transition-colors"
                                                            name="birthday" type="date"
                                                            value="{{ client.birthday }}">
                                                </td>
                                            </tr>
                                            <tr class="w-96 hover:bg-gray-100 transition-colors group">
                                                <td class="py-4 px-4 text-start">Воронка продаж:</td>
                                                <td class="py-4 px-4 text-start">
                                                    <input class="hidden" id='statusgloba' name="status" type="radio"
                                                           value="{{ client.status.id }}" checked>
                                                    <label class="hidden text-[#EF4D23]"
                                                           for="statusgloba">{{ client.status }}</label>
                                                    {% for s in statuses %}
                                                        <input class="rounded border px-[5px]"
                                                               id="status"
                                                               name="status" type="radio"
                                                               value="{{ s.id }}">
                                                        <label for="status">{{ s.name }}</label>
                                                    {% endfor %}
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="flex mt-[20px]">
                                            <button
                                                    class=' ml-[12px] border bg-green-600 text-[#ffff] text-center rounded-[10px] p-[5px] hover:border hover:text-[#000] border-green-600 hover:bg-[#ffff]'
                                                    type='submit'>Сохранить
                                            </button>
                                            <a
                                                    href="{% url 'clients_delete' client.pk %}"
                                                    class=' ml-[12px] border bg-red-600 text-[#ffff] text-center rounded-[10px] p-[5px] hover:border hover:text-[#000] border-red-600 hover:bg-[#ffff]'
                                                    type='submit'>Удалить
                                            </a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        const dataClientForm = [
            {'title': 'Ф.И.О:', 'form': `{{ form.full_name }}`},
            {'title': 'Номер телефона:', 'form': `{{ form.phone }}`},
            {'title': 'Адрес:', 'form': `{{ form.address }}`},
            {'title': 'Менеджер продаж:', 'form': `{{ form.manager }}`},
            {'title': 'Канал продаж:', 'form': `{{ form.form }}`},
            {'title': 'День рождения:', 'form': `{{ form.birthday }}`},
            {'title': 'Воронка продаж:', 'form': `{{ form.status }}`},
        ]
        const csrf = `{% csrf_token %}`

        const dataClientInfo = [
            {% for status in statuses %}
                {% for client in status.clients_set.all %}
                    {
                        'id': {{ client.id }},
                        'info': [
                            {'name':'full_name','title': 'Ф.И.О:', 'typ': `{{ client.full_name }}`, 'input': 'data'},
                            {'name':'phone','title': 'Номер телефона:', 'typ': `{{ client.phone }}`},
                            {'name':'address','title': 'Адрес:', 'typ': `{{ client.address }}`},
                            {'name':'manager','title': 'Менеджер продаж:', 'typ': `{{ client.manager }}`, 'input': 'checkbox'},
                            {'name':'form','title': 'Канал продаж:', 'typ': `{{ client.form }}`},
                            {'name':'status','title': 'Воронка продаж:', 'typ': `{{ client.status }}`},
                            {'name':'birthday','title': 'День рождения:', 'typ': `{{ client.birthday|date:'Y-m-d' }}`,'input': 'date'},
                            {'name':'creat_date','title': 'Дата добавления:', 'typ': `{{ client.creat_date|date:'Y-m-d h:m' }}`,'input': 'datetime-local', 'style':'hide'}
                        ],
                    },
                {% endfor %}
            {% endfor %}
        ]

    const dataClientEdit = [
            {% for status in statuses %}
                {% for client in status.clients_set.all %}
                    {
                        'id': {{ client.id }},
                        'info': [
                            {'name':'full_name','title': 'Ф.И.О:', 'typ': `{{ client.full_name }}`, 'input': 'data'},
                            {'name':'phone','title': 'Номер телефона:', 'typ': `{{ client.phone }}`},
                            {'name':'address','title': 'Адрес:', 'typ': `{{ client.address }}`},
                            {'name':'form','title': 'Канал продаж:', 'typ': `{{ client.form }}`},
                            {'name':'birthday','title': 'День рождения:', 'typ': `{{ client.birthday|date:'Y-m-d' }}`,'input': 'date'},
                        ],
                        'status': [
                            {'id': `{{ status.id }}`,'name':'status','title': 'Воронка продаж:', 'typ': `{{ client.status }}`},
                        ],
                        'form': [
                            {'id': `{{ client.form }}`,'name':'form','title': 'Канал продаж:', 'typ': `{{ client.form }}`},
                        ],
                    },
                {% endfor %}
            {% endfor %}
        ]
        console.log(dataClientEdit)
    </script>
{% endblock %}

crm/templates/document.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

{% endblock %}

crm/templates/edit_offic.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <section class="clients">
        <div class="clients-header">
            <div class="edit-content">
                <form action="" class="forms-clients" method="post">
                    {% csrf_token %}
                    {{ formEdit }}
                    <button class="btn-form-clients" type="submit">Изменить</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

crm/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>